server:
  port: 8903

spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
 #   sender:
 #     type: rabbit
    base-url: http://192.168.1.103:9410/
    sender:
      type: rabbit
    rabbitmq:
      queue: zhuanjiaodian.zipkin
  rabbitmq:
    addresses: 192.168.1.102
    port: 5672
    username: zipkin
    password: zipkin
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.102:3306/zjd?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        #jdbc-url: jdbc:mysql://192.168.1.102:3306/zjd?useUnicode=true&characterEncoding=utf-8
       # driver-class-name: com.mysql.jdbc.Driver
        #username: root
       # password: root
        # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
        connection-timeout: 30000
        # 最小连接数
        minimum-idle: 1
        # 最大连接数
        maximum-pool-size: 5
        # 自动提交
        auto-commit: true
        # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），默认:10分钟
        idle-timeout: 600000
        # 连接池名字
        pool-name: DatebookHikariCP
        # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms，建议设置比数据库超时时长少60秒，参考MySQL wait_timeout参数（show variables like ‘%timeout%‘;） -->
        max-lifetime: 28740000
        connection-test-query: SELECT 1

# REDIS (RedisProperties)
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 192.168.1.102
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: root
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        ## 连接池中的最大空闲连接
        max-idle: 8
        ## 连接池中的最小空闲连接
        min-idle: 0
      ## 连接超时时间（毫秒）
      shutdown-timeout: 100ms

  #mongodb
  data:
    mongodb:
      authentication-database: admin
      database: zjdsysmana
      host: 192.168.1.102
      username: root
      password: root
      port: 27017
      repositories:
        type: auto

